name: Packagist.org packag update
on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: call update packagist.org
        env:
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGIST_PACKAGE_URL: "https://packagist.org/packages/gritzkoo/php-health-checker"
        run: curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=gritzkoo&apiToken=${API_TOKEN}' -d'{"repository":{"url":"${PACKAGIST_PACKAGE_URL}"}}'
