name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: configure PHP Composer
        uses: baschny/php-composer-action@v1
      - name: run tests
        run: composer coverage
      # reference guide in https://github.com/php-coveralls/php-coveralls
      - name: send coverage to Coveralls.io
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer coveralls
